version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_DISPLAY_ERRORS: 1
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    dns:
      - 8.8.8.8
